import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal: 10,
        paddingTop: 20,
        backgroundColor: '#cecbcb',
        
      },
      container2: {
        paddingTop: 10,
        padding: 10,
        marginTop: 10,
        height: '70%',
        backgroundColor: '#ffffff',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.9,
        shadowRadius: 5,
        elevation: 5,
      },
      headerv: {
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.9,
        shadowRadius: 5,
        elevation: 5,
        flexDirection: 'row',
      },  
      footer: {
        alignItems: 'center',
        backgroundColor: '#f5a5a557',
        marginTop: 20,

        justifyContent: 'space-between',
        backgroundColor: '#ffffff',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.9,
        shadowRadius: 5,
        elevation: 5,
        flexDirection: 'row',
      },
      navigateButtonGoogle: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ee8c0b',
        padding: 10,
        borderRadius: 28,
        marginVertical: 5,
        flex: 1,
        justifyContent: 'center',
      },
      navigateButtonWaze: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1ca5a5',
        padding: 10,
        borderRadius: 28,
        marginVertical: 5,
        flex: 1,
        justifyContent: 'center',
      },
      navigateButtonChat: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#0b5017',
        padding: 10,
        borderRadius: 80,
        justifyContent: 'center',
      },      navigateButtonSupportChat: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f82929',
        padding: 30,
        borderRadius: 80,
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.9,
        shadowRadius: 5,
        elevation: 5,
        marginLeft: 20,
        width: "60%",

      },      navigateButtonStop: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1ca2d6',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.9,
        shadowRadius: 5,
        elevation: 5,
        marginRight: 20,
        padding: 30,
        borderRadius: 80,
        justifyContent: 'center',
      },
      navigateText: {
        color: '#fff',
        marginLeft: 10,
        fontWeight: 'bold',
      },
      fieldRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 8,
        flexWrap: 'wrap',
      },
      label: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#6e2a2a', 
        marginBottom: 5,
      },
      textValue: {
        fontSize: 16,
        color: '#fff', 
        fontWeight: '500',
        flex: 2,
        textAlign: 'right',
      },
       qr: {
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
      },
       qr1: {
        alignItems: 'center',
        justifyContent: 'start',
      },
      headerh: {
        marginTop: 28,
        shadowColor: '#28911b',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 2,
        shadowRadius: 5,
        elevation: 5,
        backgroundColor: '#2C4231',
        paddingVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomLeftRadius: 95,
        borderTopLeftRadius: 95,
        borderBottomRightRadius: 95,
        borderTopRightRadius: 95,
      },
      headerText: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: 'bold',
      },
      statusText: {
        color: '#A5A5A5',
        fontSize: 19,
      },
      card: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f3eee7',
        padding: 10,
        borderRadius: 30,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.9,
        shadowRadius: 5,
        marginHorizontal: 10,

        elevation: 9,
      }, cardContent: {
    
  backgroundColor: '#b88641',
        margingHorizontal: 20,

        elevation: 9,
      },
      orderIcon: {
        width: '15%',
        height: width * 0.15,
        resizeMode: 'contain',
        marginRight: 15,
      },
      cardContent: {
        flex: 1,
        justifyContent: 'space-between',
      },
      orderNumber: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 5,
      },
      location: {
        fontSize: 16,
        color: '#666',
        marginBottom: 5,
      },
      rightContainer: {
        alignItems: 'flex-end',
      },
      date: {
        fontSize: 14,
        color: '#999',
      },
      disabledView: {
        backgroundColor: '#ffffff',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 40,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.9,
        shadowRadius: 5,
        elevation: 5,
      },
      disabledText: {
        color: '#A5A5A5',
        fontSize: 18,
      },
      skeletonCard: {
        height: 100,
        backgroundColor: '#e0e0e0',
        borderRadius: 8,
        marginBottom: 15,
        padding: 10,
      },
      skeletonTitle: {
        width: '50%',
        height: 20,
        backgroundColor: '#d4d4d4',
        borderRadius: 4,
        marginBottom: 10,
      },
      shimmerContainer: {
        height: 100,
        borderRadius: 8,
        backgroundColor: '#802e2e',
        marginBottom: 10,
      },
      shimmer: {
        height: '100%',
        borderRadius: 8,
        backgroundColor: '#b83e3e',
      },
      skeletonDescription: {
        width: '80%',
        height: 15,
        backgroundColor: '#d4d4d4',
        borderRadius: 4,
      },
});

export default styles;
